server:
  port: 8081
spring:
  redis:
    # 连接超时时间（记得添加单位，Duration）
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    # database: 0
    host: 127.0.0.1
    database: 0
    port: 6379
    password: 123
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  cache:
    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
    type: redis
  application:
    name: redis
logging:
  level:
    com.zj: debug
########################################################################
#
#     redisson单机配置
#
#########################################################################
redisson:
  lock:
    server:
      address: 127.0.0.1:6379
      type: standalone
      password:${spring.redis.password}
      database: 1
########################################################################
#
#     redisson哨兵配置
#     **redisson.lock.server.address** 格式为: sentinel.conf配置里的sentinel别名,
#     sentinel1节点的服务IP和端口，sentinel2节点的服务IP和端口，sentinel3节点的服务IP和端口
#
#     比如sentinel.conf里配置为sentinel monitor my-sentinel-name 127.0.0.1 6379 2,那么这里就配置my-sentinel-name
#
#########################################################################
#redisson.server.address=my-sentinel-name,127.0.0.1:26379,127.0.0.1:26389,127.0.0.1:26399
#redisson.server.type=sentinel
#redisson.lock.server.password=
#redisson.lock.server.database=1
########################################################################
#
#     redisson分布式锁配置--集群方式
#     cluster方式至少6个节点(3主3从，3主做sharding，3从用来保证主宕机后可以高可用)
#     地址格式为: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384
#########################################################################
#redisson.server.address=127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384
#redisson.server.type=cluster
#redisson.lock.server.password=
########################################################################
#
#     redisson分布式锁配置--主从
#     地址格式为**主节点,子节点,子节点**
#     代表主节点:127.0.0.1:6379，从节点127.0.0.1:6380，127.0.0.1:6381

#########################################################################
#redisson.server.address=127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381
#redisson.server.type=masterslave
#redisson.lock.server.password=
#redisson.lock.server.database=1

#  //主从模式
#spring:
#  redis:
#    sentinel:
#      master: my-master
#      nodes: localhost:26379,localhost:26389
#    password: your_password
#redisson:
#  master-slave-config:
#    master-address: "redis://localhost:6379"
#    slave-addresses: "redis://localhost:6380,redis://localhost:6381"
#    password: ${spring.redis.password}
#
#  // 集群模式
#spring:
#  redis:
#    cluster:
#      nodes: localhost:6379,localhost:6380,localhost:6381,localhost:6382,localhost:6383,localhost:6384
#    password: your_password
#redisson:
#  cluster-config:
#    node-addresses: "redis://localhost:6379,redis://localhost:6380,redis://localhost:6381,redis://localhost:6382,redis://localhost:6383,redis://localhost:6384"
#    password: ${spring.redis.password}
#
#  // 哨兵模式
#spring:
#  redis:
#    sentinel:
#      master: my-master
#      nodes: localhost:26379,localhost:26389
#    password: your_password
#redisson:
#  sentinel-config:
#    master-name: my-master
#    sentinel-addresses: "redis://localhost:26379,redis://localhost:26380,redis://localhost:26381"
#    password: ${spring.redis.password}
